// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: false,
  APIs: {
    URL: 'http://127.0.0.1:8000',
    BRASILAPI: 'https://brasilapi.com.br/api/cep/v1',
  },
};
