// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: false,
  APIs: {
    URL: 'https://apigateway-tst.nexxera.com',
    BRASILAPI: 'https://brasilapi.com.br/api/cep/v1',
  },
};
