// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: false,
  APIs: {
    URL: 'http://api.ufa.app.br',
    BRASILAPI: 'https://brasilapi.com.br/api/cep/v1',
  },
};
